### ISSUE TITLE
can not process csv file from XiSEARCH with xiFDR (Semicolons in FASTA-Header)

### ISSUE THREAD

**Issue by frmueller** [Rappsilber-Laboratory/xiFDR#24]
Hi Lutz,

I am trying to do an FDR estimation from a large search but I always get parsing errors in java. I can not find the error, because the error message from the log is not very helpful.

here the massage:
Mai 08, 2020 11:19:12 AM org.rappsilber.gui.components.JoinedThreadedTextOuput publish
INFO: Start
Mai 08, 2020 11:19:12 AM org.rappsilber.gui.components.JoinedThreadedTextOuput publish
INFO: Read from peroxi_iso_17032020_top1252fasta_Xi1.7.0.csv
Mai 08, 2020 11:19:12 AM org.rappsilber.fdr.gui.FDRGUI addCSV
INFO: read from Z:\fmueller\FM002\xiSearch\peroxi_iso_17032020_top1252fasta_Xi1.7.0.csv
Mai 08, 2020 11:19:12 AM org.rappsilber.fdr.CSVinFDR readCSV
SEVERE: Unexecpted exception while parsing line 3
java.text.ParseException: Don't know how to handle different numbers of proteins and peptide positions
	at org.rappsilber.fdr.CSVinFDR.readCSV(CSVinFDR.java:368)
	at org.rappsilber.fdr.gui.FDRGUI.addCSV(FDRGUI.java:936)
	at org.rappsilber.fdr.gui.FDRGUI$9.run(FDRGUI.java:840)
	at java.base/java.lang.Thread.run(Thread.java:830)

Mai 08, 2020 11:19:12 AM org.rappsilber.gui.components.JoinedThreadedTextOuput publish
INFO: finished reading

When I check the file, than there are not multiple proteins or peptides positions. It would be helpful when the csv file from XiSEARCH would be compatible with xiFDR.

Best wishes

**Comment by lutzfischer** [comment]
Hi Fränze,

I suspect that the problem is with the xiSEARCH/FASTA-file. It looks like the protein `P87262` contains `RPL34A;RPL34B GN=RPL34A;RPL34B` as part of the FASTA-header. This confuses then xiFDR, as it assumes a `;` denotes separate proteins. So you have *_n_* proteins but xiFDR thinks there are *_v+3_* protein descriptions.
Have to think about how I can address that in xiSEARCH and xiFDR, but for now I would suggest to change the fasta header to not contain `;`

**Comment by frmueller** [comment]
Hi Lutz,

I also had the supition that's it is the fasta header, so tried to format it differently but it did not work. The fasta header in this search looks like this:
>sp|P38507|SPA_STAAU Immunoglobulin G-binding protein A OS=Staphylococcus aureus GN=spa PE=1 SV=1

and I really don't know where xi takes the ";" form.

**Comment by lutzfischer** [comment]
can you look at P87262?

**Comment by frmueller** [comment]
Indeed, P87262 looks like:
>sp|P87262 RPL34A;RPL34B GN=RPL34A;RPL34B

But its a normal Uniprot entry. I guess this means that I have to check each Uniprot Fasta before I use it for xiSEARCH, right?

**Comment by lutzfischer** [comment]
can you just search and replace ; with _ or space (or anything else then ;) - need to address that in both xiSEARCH and xiFDR

**Comment by frmueller** [comment]
o.k. I will do so. Thanks Lutz

**Comment by lutzfischer** [comment]
Actually the header should be
`>sp|P87262|RL34A_YEAST 60S ribosomal protein L34-A OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=RPL34A PE=1 SV=1`

Not sure where the change came from - guess you had some pre-processing that resulted in protein groups. And that protein group is somehow encoded in the FASTA?
