### ISSUE TITLE
A fatal exception has occurred. Program will exit.

### ISSUE THREAD

**Issue by yuanxiaoustc** [Rappsilber-Laboratory/xiFDR#27]
All Results : 9637
 Top Matches : 9637
四月 26, 2022 9:25:58 上午 rappsilber.ui.LoggingStatus setStatus
信息: completed
四月 26, 2022 9:25:58 上午 rappsilber.ui.LoggingStatus setStatus
信息: completed
四月 26, 2022 9:25:58 上午 rappsilber.ui.LoggingStatus setStatus
信息: calling xiFDR: C:\Program Files\Java\jdk1.8.0_201\bin\java.EXE -Dfile.encoding=UTF-8 --add-opens java.base/java.lang=ALL-UNNAMED -jar C:\Users\Administrator\Desktop\Xisearch\xiSEARCH_1.7.6.5\xiSEARCH_1.7.6.5\xiFDR-2.1.5.5.jar --linkfdr=5.0 --boost=link --csvOutDir=C:\Users\Administrator\Desktop\CCAN-TRY\FDR_rpfdr5.0 --csvBaseName=123456_Xi1.7.6.5 --xiconfig=C:\Users\Administrator\Desktop\CCAN-TRY\123456_Xi1.7.6.5.csv.config --fasta=C:\Users\Administrator\Desktop\CCAN-TRY\polII-uniprot.fasta --gui C:\Users\Administrator\Desktop\CCAN-TRY\123456_Xi1.7.6.5.csv
Error: Could not create the Java Virtual Machine.
四月 26, 2022 9:25:58 上午 rappsilber.ui.LoggingStatus setStatus
信息: Error while running FDR
Error: A fatal exception has occurred. Program will exit.
Unrecognized option: --add-opens

How to solve this error？

**Comment by lutzfischer** [comment]
can you try to replace the xiSEACRH.jar file with the one from [here](http://rappsilberlab.org/xiversion/dev/)?
