### ISSUE TITLE
xiFDR - Error parsing file

### ISSUE THREAD

**Issue by jayieh** [Rappsilber-Laboratory/xiFDR#29]
Hi,

I am trying to run xiFDR 2.1.5.5 on a xlink search I conducted with xiSEARCH 1.7.6.7.

When I use the GUI of xiFDR on the exact same file, it works, however, when trying to process the xiSEARCH output via the cmd line, this fails.

below you can find the cmd I am using and the error resulting from it.

I'd be happy for any advice and please let me know, if you need further information from me.

Best

Jürgen

java -Xmx17g -jar /home/j/jeirich/xiSEARCH/xiSEARCH_1.7.6.7/xiFDR-2.1.5.5.jar --linkfdr=5.0 --boost=link --csvOutDir=/home/j/jeirich/rawfiles_on_scratch/22_051_ABr_VTT/VTT/VTT_FDR --csvBaseName=VTT_xlinks --xiconfig=/home/j/jeirich/xiSEARCH/xiSEARCH_1.7.6.7/ABr_VTT.conf --fasta=/home/j/jeirich/rawfiles_on_scratch/22_051_ABr_VTT/uniprot-chloroplast.fasta --map=run:Run,scan:Scan,"peak list file":peakListFileName,"peak list index":ScanId,rank:MatchRank,peptide1:Peptide1,peptide2:Peptide2,"peptide length 1":LengthPeptide1,"peptide length 2":LengthPeptide2,"peptide link 1":Link1,"peptide link 2":Link2,"is decoy 1":Protein1decoy,"is decoy 2":Protein2decoy,"precursor charge":PrecoursorCharge,score:"match score","peptide1 score":Pep1Score,"peptide2 score":Pep2Score,accession1:Protein1,accession2:Protein2,description1:Fasta1,description2:Fasta2,"peptide position 1":Start1,"peptide position 2":Start2,crosslinker:Crosslinker,crossLinkerModMass:CrosslinkerMass,"experimental mz":PrecurserMZ,"calculated mass":CalcMass,"delta score":delta,"peptide coverage1":"peptide1 unique matched non lossy coverage","peptide coverage2":"peptide2 unique matched non lossy coverage","peptide1 fragments":"peptide1 unique matched conservative","peptide2 fragments":"peptide2 unique matched conservative","peptides with stubs":"fragment CCPepFragment","peptides with doublets":"fragment CCPepDoubletFound" /home/j/jeirich/rawfiles_on_scratch/22_051_ABr_VTT/VTT/VTT_xlinks.tsv

writing results to /home/j/jeirich/rawfiles_on_scratch/22_051_ABr_VTT/VTT/VTT_FDR/VTT_xlinks*
Jan 12, 2023 12:43:40 PM org.rappsilber.fdr.XiCSVinFDR main
INFO: seeting up csv input
Jan 12, 2023 12:43:40 PM org.rappsilber.fdr.XiCSVinFDR main
INFO: Read datafrom CSV
Jan 12, 2023 12:43:40 PM org.rappsilber.fdr.XiCSVinFDR main
SEVERE: Error parsing file: /home/j/jeirich/rawfiles_on_scratch/22_051_ABr_VTT/VTT/VTT_xlinks.tsv
java.text.ParseException: Column peptide1 not found
        at org.rappsilber.fdr.CSVinFDR.getColumn(CSVinFDR.java:147)
        at org.rappsilber.fdr.CSVinFDR.readCSV(CSVinFDR.java:172)
        at org.rappsilber.fdr.XiCSVinFDR.readCSV(XiCSVinFDR.java:634)
        at org.rappsilber.fdr.XiCSVinFDR.main(XiCSVinFDR.java:398)
        at org.rappsilber.fdr.CommandLine.main(CommandLine.java:49)

**Comment by jayieh** [comment]
thanks for the quick reply. 

yes. this is what I tried first, but as xiFDR is complaning about the missing peptide1 col, so I tried to fix it via mapping...

java -Xmx17g -jar /home/j/jeirich/xiSEARCH/xiSEARCH_1.7.6.7/xiFDR-2.1.5.5.jar --linkfdr=5.0 --boost=link --csvOutDir=/home/j/jeirich/rawfiles_on_scratch/22_051_ABr_VTTTT/VTT/VTT_FDR --csvBaseName=VTT_xlinks --xiconfig=/home/j/jeirich/xiSEARCH/xiSEARCH_1.7.6.7/ABr_VTT.conf --fasta=/home/j/jeirich/rawfiles_on_scratch/22_051_ABr_VTTTT/uniprot-chloroplast.fasta /home/j/jeirich/rawfiles_on_scratch/22_051_ABr_VTTTT/VTT/VTT_xlinks.tsv

writing results to /home/j/jeirich/rawfiles_on_scratch/22_051_ABr_VTTTT/VTT/VTT_FDR/VTT_xlinks*
Jan 12, 2023 5:08:12 PM org.rappsilber.fdr.XiCSVinFDR main
INFO: seeting up csv input
Jan 12, 2023 5:08:12 PM org.rappsilber.fdr.XiCSVinFDR main
INFO: Read datafrom CSV
Jan 12, 2023 5:08:12 PM org.rappsilber.fdr.XiCSVinFDR main
SEVERE: Error parsing file: /home/j/jeirich/rawfiles_on_scratch/22_051_ABr_VTTTT/VTT/VTT_xlinks.tsv
java.text.ParseException: Column peptide1 not found
        at org.rappsilber.fdr.CSVinFDR.getColumn(CSVinFDR.java:147)
        at org.rappsilber.fdr.CSVinFDR.readCSV(CSVinFDR.java:172)
        at org.rappsilber.fdr.XiCSVinFDR.readCSV(XiCSVinFDR.java:634)
        at org.rappsilber.fdr.XiCSVinFDR.main(XiCSVinFDR.java:398)
        at org.rappsilber.fdr.CommandLine.main(CommandLine.java:49)

**Comment by lutzfischer** [comment]
can you post jut the first line of the file?

**Comment by jayieh** [comment]
sure:

`Run	Scan	ScanTitle	peakListFileName	ScanId	Source	ElutionStart	ElutionEnd	PrecursorMass	PrecoursorCharge	PrecurserMZ	PrecurserIntensity	CalcMass	CalcMZ	validated	decoy	MatchRank	Crosslinker	CrosslinkerMass	 decoyCrosslinker	Protein1	Fasta1	Protein1decoy	Peptide1	BasePeptide1	PeptideLinkMap1	PeptideMass1	PeptideWeight1	Start1	LengthPeptide1	Link1	Linked AminoAcid 1	LinkWindow1	ProteinLink1	ProteinCount1	PositionCount1	Modifications1	ModificationPositions1	ModificationMasses1	OpenModPosition1	OpenMass1	OpenModWindow1	Protein2	Fasta2	Protein2decoy	Peptide2	BasePeptide2	PeptideLinkMap2	PeptideMass2	PeptideWeight2	Start2	LengthPeptide2	Link2	Linked AminoAcid 2	LinkWindow2	ProteinLink2	ProteinCount2	PositionCount2	Modifications2	ModificationPositions2	ModificationMasses2	OpenModPosition2	OpenMass2	OpenModWindow2	alphaCount	alphaConsidered	betaCount	betaCountInverse	mgcRank	mgxRank	mgcScore	mgcDelta	mgcShiftedDelta	mgcAlpha	mgcBeta	mgcAlphaBeta	Palpha_beta	mgxScore	mgxDelta	delta	deltaMod	combinedDelta	Precoursor Error	Precoursor Absolute Error	PrecoursorAbsoluteErrorRelative	1-ErrorRelative	AverageMS2Error	MeanSquareError	MeanSquareRootError	AverageRelativeMS2Error	Average1-RelativeMS2Error	AverageMS2ErrorPeptide1	AverageMS2ErrorPeptide2	AverageMS2ErrorCrossLinked	AverageNonAbsoluteMS2Error	MaxCharge	AverageCharge	RelativeMaxCharge	RelativeAverageCharge	total fragment matches	lossy fragment matches	fragment matched	fragment coverage	fragment non lossy matched	fragment non lossy coverage	fragment lossy matched	fragment lossy coverage	fragment matched conservative	fragment conservative coverage	fragment unique matched	fragment unique matched non lossy	fragment unique matched non lossy coverage	fragment unique matched lossy	fragment unique matched lossy coverage	fragment unique matched conservative	fragment unique crosslinked matched	fragment unique crosslinked matched non lossy	fragment unique crosslinked matched non lossy coverage	fragment unique crosslinked matched lossy	fragment unique crosslinked matched lossy coverage	fragment unique crosslinked matched conservative	fragment multimatched%	fragment sequencetag coverage%	fragment unique matched conservative coverage	fragment CCPepFragment	fragment CCPepFragmentError	fragment CCPepFragmentCount	fragment CCPepFragmentIntensity	fragment CCPepDoubletCount	fragment CCPepDoubletFound	peptide1 total fragment matches	peptide1 lossy fragment matches	peptide1 matched	peptide1 coverage	peptide1 non lossy matched	peptide1 non lossy coverage	peptide1 lossy matched	peptide1 lossy coverage	peptide1 matched conservative	peptide1 conservative coverage	peptide1 unique matched	peptide1 unique matched non lossy	peptide1 unique matched non lossy coverage	peptide1 unique matched lossy	peptide1 unique matched lossy coverage	peptide1 unique matched conservative	peptide1 unique matched conservative coverage	peptide1 unique crosslinked matched	peptide1 unique crosslinked matched non lossy	peptide1 unique crosslinked matched non lossy coverage	peptide1 unique crosslinked matched lossy	peptide1 unique crosslinked matched lossy coverage	peptide1 unique crosslinked matched conservative	peptide1 multimatched%	peptide1 sequencetag coverage%	peptide1 CCPepFragment	peptide1 CCPepFragmentError	peptide1 CCPepFragmentCount	peptide1 CCPepFragmentIntensity	peptide1 CCPepDoubletCount	peptide1 CCPepDoubletFound	peptide2 total fragment matches	peptide2 lossy fragment matches	peptide2 matched	peptide2 coverage	peptide2 non lossy matched	peptide2 non lossy coverage	peptide2 lossy matched	peptide2 lossy coverage	peptide2 matched conservative	peptide2 conservative coverage	peptide2 unique matched	peptide2 unique matched non lossy	peptide2 unique matched non lossy coverage	peptide2 unique matched lossy	peptide2 unique matched lossy coverage	peptide2 unique matched conservative	peptide2 unique matched conservative coverage	peptide2 unique crosslinked matched	peptide2 unique crosslinked matched non lossy	peptide2 unique crosslinked matched non lossy coverage	peptide2 unique crosslinked matched lossy	peptide2 unique crosslinked matched lossy coverage	peptide2 unique crosslinked matched conservative	peptide2 multimatched%	peptide2 sequencetag coverage%	peptide2 CCPepFragment	peptide2 CCPepFragmentError	peptide2 CCPepFragmentCount	peptide2 CCPepFragmentIntensity	peptide2 CCPepDoubletCount	peptide2 CCPepDoubletFound	FragmentLibraryScore	FragmentLibraryScoreExponential	FragmentLibraryScoreLog	spectrum intensity coverage	spectra intensity nonlossy coverage	spectra isotop%	spectra matched isotop%	spectra matched single%	spectra top10 matched%	spectra top20 matched%	spectra top40 matched%	spectra top100 matched%	spectrum peaks coverage	SpectraCoverageConservative	BS3ReporterIonScore	Crosslinked	Modified	Containing	Pep1Score	Pep2Score	spectrum quality score	AllScore	AllScoreLib	MatchScore	NormScore	J48ModeledManual001	RandomTreeModeledManual	Autovalidation	match score`

**Comment by lutzfischer** [comment]
I suspect there is a problem in detecting the field delimiter. Can you try to add an argument --delimiter=\t, --delimiter=\\t or, if your on linux, --delimter=$'\t'

**Comment by jayieh** [comment]
Hi,

It's CENTOS7. The delimiter was my first guess, too. But even with 

`--delimiter=$'\t' `

still the error stays the same:

`java.text.ParseException: Column peptide1 not found`...

Any other idea that I could try?

**Comment by lutzfischer** [comment]
short update - it somehow fails to recognise the tab as delimiter. can you save it as csv - comma separated values? Will fix the tab problem as soon as I find the reason - used to work not sure why it is not now

**Comment by lutzfischer** [comment]
ok got a bit closer - somehow it "detects" the wrong character as delimiter and you have to give both delimiter and quote character to stop it from trying to detect these. So you could also add --delimiter=\\t and --quote=\" as arguments and that should make it use the right values

**Comment by jayieh** [comment]
Hi, thanks for following up on this so quickly.

convertig tab to comma seems to work.

(when explicitly setting --delimiter=\t and --quote='' I got another error...)
