### ISSUE TITLE
Are "peptide link" and "peptide position" 0-based or 1-based?

### ISSUE THREAD

**Issue by michabirklbauer** [Rappsilber-Laboratory/xiFDR#38]
Hi!

I am currently trying to use xiFDR with my own crosslink search engine and am in the process of creating the necessary CSV for it. As stated in the title, I am not sure whether xiFDR expects the positions to be 0-based or 1-based (for columns `peptide link 1`, `peptide link 2`, `peptide position 1` and `peptide position 2`.

As an example, if I have peptide [K]HQQGR with crosslinker attached to the first K, would `peptide link` be 0 or 1?

As for the `is decoy` column, I guess accepted values are `true` and `false`. Or does it need specific capitalization (e.g. `True` instead of `true`)?

Thanks a lot in advance!

Best, Micha

**Comment by michabirklbauer** [comment]
Also for `accession` and `peptide position` - how should multiple entries be delimited if a peptide maps to more than one accession?

**Comment by michabirklbauer** [comment]
A problem that is probably unrelated to all this:
When I try to load my CSV file, I first get these warnings and then what looks to me like errors in the commandline while the GUI becomes unresponsive. I have followed the instructions from the readme in terms of necessary columns and column names, I have no clue what's happening here:
![image](https://github.com/Rappsilber-Laboratory/xiFDR/assets/19354640/45bef182-998c-4584-9060-3eaf527a7f8d)
![image](https://github.com/Rappsilber-Laboratory/xiFDR/assets/19354640/0bb49fd9-18fc-4c92-818c-96ce5fee90a9)
![image](https://github.com/Rappsilber-Laboratory/xiFDR/assets/19354640/655a3b6a-c448-4010-9ce9-1e3915de7654)
![image](https://github.com/Rappsilber-Laboratory/xiFDR/assets/19354640/01cae494-dfd2-424c-8565-0b0bb65b87af)
Any help would be appreciated!

**Comment by michabirklbauer** [comment]
This would be the CSV file I am trying to load
[CSMs_xiFDR.csv](https://github.com/Rappsilber-Laboratory/xiFDR/files/14606111/CSMs_xiFDR.csv)
Oh, and I am on Windows 10, xiFDR 2.1.5.2 and java --version
```
openjdk 11.0.16.1 2022-08-12 LTS
OpenJDK Runtime Environment Microsoft-40648 (build 11.0.16.1+1-LTS)
OpenJDK 64-Bit Server VM Microsoft-40648 (build 11.0.16.1+1-LTS, mixed mode)
```

**Comment by michabirklbauer** [comment]
> Also for `accession` and `peptide position` - how should multiple entries be delimited if a peptide maps to more than one accession?

After some more testing and trying to figure this out myself, I figured that this was actually the issue why xiFDR didn't like my CSV file - I delimited multiple accessions/peptide positions with a semicolon which it didn't like.

Does xiFDR support this at all? How should cases be handled when a peptide maps to more than one protein?
For the moment I'm just reporting the first protein now, if there is multiple. However, I don't think that is ideal.

**Comment by lutzfischer** [comment]
Sorry for the late answer. xiFDR expects all numbers 1 based (users get confused with 0 based counting for some reason). 

As for ambiguous peptide positions it expects that all protein related fields hold as many entries as the peptide position fields. if a peptide could come from a hundred places in one protein and 1 place in another protein accession and description fields both need to contain 101 semicolon separated values.

Will have a look at the csv file

**Comment by lutzfischer** [comment]
Ok just tried with the lates version of xiFDR (2.2.1) and I can read the file without any problem. Can you try with that version.
