### ISSUE TITLE
Filtering based on matching score?

### ISSUE THREAD

**Issue by llmlrnr** [Rappsilber-Laboratory/xiFDR#49]
Is it necessary to filter out the results based on the peptide matching score after performing the estimation of FDRs?

For example, would you avoid reporting a PPI based on a small matching score value for the detected crosslinked peptide? If so, what would be your threshold for deciding which crosslinks are worth reporting and which are not?

**Comment by grandrea** [comment]
If you are interedted in PPIs, you should utilize xiFDR, filter on both
residue pair level (5% for example) and protein pair level (also 5%) and
then report all links passing fdr to have appropriate statistical control.
See for  lenz et al nat comms 2021 for more on this.

You then can deposit mzIdentML in PRIDE/ProteomeXChange and attatch the
links csv as supplementary data to your paper.

Filtering based on score post-fdr sort of defeats the purpose of a
target-decoy fdr in the first place...
